<a href="https://colab.research.google.com/github/raffaellaalpaca-ai/walmart-hurricane-project/blob/main/2026_10_23_%E2%80%94_Midterm_Checkpoint_%E2%80%94_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS2002 · Midterm Checkpoint

**Lab — 2026-10-23 · Fall 2026**  

---

## Lab 09 — Midterm checkpoint, week 1 of 3

**What you submit: the link to your team's main repo. Only that.** One submission per team. Do not upload separate files.

Put this notebook in the repo (the `notebooks/` folder is fine) and push it, so everything we check is in one place.

**You do not have to fill this all out.** It is a checkpoint, not a finished project. Skip any section you have not started and write "not started" next to it. What we must see is:

1. **Your charter**, committed to the repo
2. **Any progress** you have made, with code that ran and output you can point at

Start with the team setup, then work down the same eight things we listed at Monday's kickoff, as far as you have gotten. This is graded on evidence, not on intentions.

The purpose is to catch a stalled team while there is still time to unstall it. If something is not working, say so here plainly. A checkpoint that honestly reports "the API join is not working and here is the error" is worth more than one that claims progress that does not exist, and it gets you help on Monday.

### Team setup

This part is required. Fill it in once for the whole team.

You need:

- Your team name, and every member with a GitHub handle (2 to 4 people)
- A link to your team's **main repo**. This is the one link you submit.
- A link to `CHARTER.md` in that repo, the page on GitHub, not a file on someone's laptop

Nice to have, and also in your charter: this week's notebook owner, your meeting time, and the five worst problems in the data from the profile you ran on Monday. Be specific: "`unit_price` is stored as text and some values start with `$`" beats "prices are messy."

In [1]:
team_setup = {
    'team_name': 'Team Kylie',
    'members': [
        {'name': 'Emma Kee', 'github': 'ekee7'},
        {'name': 'Kylie Sharp', 'github': 'kyliefsharp'},
        {'name': 'Raffaella Alpaca', 'github': 'raffaellaalpaca-ai'},
        {'name': 'Miriam Ahmadd', 'github': 'miriamahmadd'},
    ],
    'repo_url': 'https://github.com/raffaellaalpaca-ai/walmart-hurricane-project',
    'charter_url': 'https://github.com/raffaellaalpaca-ai/walmart-hurricane-project/blob/main/CHARTER.md',
    'notebook_owner_this_week': 'Kylie',
    'meeting_time': 'Wednesday at 10am',
    'five_worst_problems': ['Our schedules do not line up very well', 'We have a lot of midterms', 'We have academic/non-academic commitments', 'We have other projects', 'Data cleaning is time consuming'],
}

def check_team(t, quiet=False):
    def real(v):
        return isinstance(v, str) and v.strip() != '' and not v.startswith('TODO')
    required = {
        'team name': real(t['team_name']),
        '2 to 4 members, each with a name and GitHub handle':
            2 <= len(t['members']) <= 4 and all(real(m['name']) and real(m['github']) for m in t['members']),
        'main repo link': real(t['repo_url']) and t['repo_url'].startswith('https://github.com/'),
        'charter link points at CHARTER.md': real(t['charter_url']) and t['charter_url'].endswith('CHARTER.md'),
    }
    nice = {
        'notebook owner': real(t['notebook_owner_this_week']),
        'meeting time': real(t['meeting_time']),
        'five specific problems': len(t['five_worst_problems']) >= 5 and all(real(p) for p in t['five_worst_problems']),
    }
    if not quiet:
        print('REQUIRED')
        for label, good in required.items():
            print('  PASS' if good else '  FAIL', '-', label)
        print('NICE TO HAVE')
        for label, good in nice.items():
            print('  done' if good else '  not yet', '-', label)
        print()
        print('team setup complete:', all(required.values()))
    return all(required.values())

check_team(team_setup)

REQUIRED
  PASS - team name
  PASS - 2 to 4 members, each with a name and GitHub handle
  PASS - main repo link
  PASS - charter link points at CHARTER.md
NICE TO HAVE
  done - notebook owner
  done - meeting time
  done - five specific problems

team setup complete: True

True

Now show that the charter is actually committed. This is required. Run the next cell and leave its output in the notebook. Point `REPO_PATH` at your local clone of the team repo. If it prints a line like `a1b2c3d Add team charter`, you are done. If it prints "no commits found," the charter is not in the repo yet, so commit it and push before you submit.

In [2]:
!git clone https://github.com/ekee7/walmart-hurricane-project.git

fatal: destination path 'walmart-hurricane-project' already exists and is not an empty directory.

In [3]:
import subprocess

REPO_PATH = '/content/walmart-hurricane-project' # Your local clone of the team repo

result = subprocess.run(['git', '-C', REPO_PATH, 'log', '--oneline', '--', 'CHARTER.md'],
                        capture_output=True, text=True)
print(result.stdout.strip() or 'no commits found for CHARTER.md')

b182050 Fixed formatting in CHARTER.md
81e6364 Updated Charter
809052a Updated roles in charter
2a3176e Updated charter with group rules
686fa68 Add project charter outlining goals and responsibilities

In [4]:
import pandas as pd

# Import data set from GitHub
url = 'https://raw.githubusercontent.com/ekee7/walmart-hurricane-project/refs/heads/main/data/walmart_transactions.csv'
df = pd.read_csv(url)

In [5]:
df.head()

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,PEANUT BUTTER,Grocery,1,3.15
1,TXN000759,fl-412,2024-09-13 20:30:20,CNSOUP-01,CANNED SOUP,GROCERY,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,ELECTRONICS,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24pk,Alcoholic Beverages,3,18.82

In [6]:
df.shape

# There are 25562 rows and 8 columns in this dataset

(25562, 8)

### 2 — Your decision log

**TODO:** every cleaning decision, what it did, and how many rows it touched. If your teammates disagree with one of these, note the disagreement — that is useful information, not a problem to hide.

In [7]:
DECISIONS = []

# Function for decision logging
def log(step, decision, rows_affected):
    DECISIONS.append({'step': step, 'decision': decision, 'rows': rows_affected})
    print(f'[{step}] {decision} ({rows_affected} row(s))')

### 1 — Your cleaning pipeline as functions

**TODO:** paste the cleaning code you have written so far. It should be functions, not loose cells, and it should cover at minimum: duplicates, `unit_price` to numeric (it comes in as text, some with a `$`), the negative `quantity` values with your decision applied, `timestamp` parsed, and `store_id` cleaned up so it will join to the store file.

Print the row count before and after. We want to see how many rows your decisions removed.

In [52]:
# Preserve the original dataframe

df_original = df.copy()

In [8]:
# Standardize text case to uppercase and strip

def to_uppercase(column_name):
  standardized = df[column_name].str.strip().str.upper()
  rows_affected = df[column_name].ne(standardized).sum() # Count number of rows affected
  df[column_name] = standardized

  return df, rows_affected

# Standardize store_id values by stripping leading/trailing whitespace and converting all characters to uppercase.
# This ensures consistent formatting for matching store IDs when joining with the store dataset.
# EX: FL-710 vs. fl-412 - We want all to be FL-710

df, rows_affected = to_uppercase('store_id')

log(
    'Data cleaning',
    'store_id: standardize text case to uppercase and strip',
    rows_affected
)

df.head()

[Data cleaning] store_id: standardize text case to uppercase and strip (1795 row(s))

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,PEANUT BUTTER,Grocery,1,3.15
1,TXN000759,FL-412,2024-09-13 20:30:20,CNSOUP-01,CANNED SOUP,GROCERY,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,ELECTRONICS,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24pk,Alcoholic Beverages,3,18.82

In [9]:
# Standardize text case to title case and strip

def to_title_case(column_name):
  standardized = df[column_name].str.strip().str.title()
  rows_affected = df[column_name].ne(standardized).sum() # Count number of rows affected
  df[column_name] = standardized

  return df, rows_affected

# Standardize product_name and category column information
# EX: PEANUT BUTTER - We want it to be Peanut Butter

df, rows_affected = to_title_case('product_name')
log('Data cleaning', 'product_name: standardize text case to title case and strip', rows_affected)

df, rows_affected = to_title_case('category')

log(
    'Data cleaning',
    'category: standardize text case to title case and strip',
    rows_affected
)

df.head()

[Data cleaning] product_name: standardize text case to title case and strip (12875 row(s))
[Data cleaning] category: standardize text case to title case and strip (13175 row(s))

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,Peanut Butter,Grocery,1,3.15
1,TXN000759,FL-412,2024-09-13 20:30:20,CNSOUP-01,Canned Soup,Grocery,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,Electronics,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24Pk,Alcoholic Beverages,3,18.82

In [10]:
# Look at the datatypes of the columns

print('Column datatypes:\n', df.dtypes)

Column datatypes:
 transaction_id    object
store_id          object
timestamp         object
sku               object
product_name      object
category          object
quantity           int64
unit_price        object
dtype: object

In [11]:
# Update unit_price to be float type, remove $, and strip

def to_float(column_name):
  standardized = df[column_name].str.strip().str.replace('$', '', regex=False).astype(float)
  rows_affected = df[column_name].ne(standardized).sum() # Count number of rows affected
  df[column_name] = standardized

  return df, rows_affected

# unit_price is a String but it should be a float type for future calculations (i.e. summing/etc)
df, rows_affected = to_float('unit_price')

log(
    'Data cleaning',
    'unit_price: update to be float type and remove $',
    rows_affected
)

df.head()

[Data cleaning] unit_price: update to be float type and remove $ (25562 row(s))

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,Peanut Butter,Grocery,1,3.15
1,TXN000759,FL-412,2024-09-13 20:30:20,CNSOUP-01,Canned Soup,Grocery,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,Electronics,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24Pk,Alcoholic Beverages,3,18.82

In [12]:
# Post-function analysis

print('Post-to_float()\n')
print('Datatype:', df['unit_price'].dtype)

Post-to_float()

Datatype: float64

In [13]:
# Duplicate rows function

def drop_duplicate_rows(df):
  rows_affected = df.duplicated().sum() # Count number of rows affected
  df.drop_duplicates(inplace=True)

  return df, rows_affected

# Remove exact duplicate rows because they represent repeated records that could inflate transaction counts and sales totals
# Only rows identical across all columns are removed
# EX: rows that share a transaction_id are not automatically considered duplicates

df, rows_affected = drop_duplicate_rows(df)

log(
    'Data cleaning',
    'Drop duplicate rows',
    rows_affected
)

df.head()

[Data cleaning] Drop duplicate rows (30 row(s))

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,Peanut Butter,Grocery,1,3.15
1,TXN000759,FL-412,2024-09-13 20:30:20,CNSOUP-01,Canned Soup,Grocery,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,Electronics,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24Pk,Alcoholic Beverages,3,18.82

In [14]:
# Post-function analysis

print('Post-to_float()\n')
print('Number of rows:', df.shape[0])

Post-to_float()

Number of rows: 25532

In [15]:
# Negative quantity value function

def change_negative_quantities(column_name):
  rows_affected = (df[column_name] < 0).sum() # Count number of rows affected
  df[column_name] = df[column_name].abs()

  return df, rows_affected

# Convert negative quantity values to positive values using abs() so all quantities represent nonnegative units sold
# We decided to make the quantity values positive because negative quantities do not make sense
# Instead of dropping the rows, we decided to view negative quantities as user entry mistakes
df, rows_affected = change_negative_quantities('quantity')

log(
    'Data cleaning',
    'quantity: Changed negative quantity values to positive values',
    rows_affected
)

[Data cleaning] quantity: Changed negative quantity values to positive values (130 row(s))

In [16]:
# Pre-function analysis

print('Pre-parse_timestamp()\n')
print('Unique values', df['timestamp'].unique())
print('Has NaN values:', df['timestamp'].hasnans)
print('NaN count:', df['timestamp'].isna().sum())

Pre-parse_timestamp()

Unique values ['2024-09-24T09:48:13' '2024-09-13 20:30:20' '2024-09-17 10:06:00' ...
 '09-26-2024 08:47:08' '16-Sep-2024 16:39' '2024-09-25 17:08:35']
Has NaN values: True
NaN count: 884

Originally, we had a standardized = pd.to_datetime(df[column_name], errors='coerce'). errors='coerce' tells Pandas to convert valid timestamp strings into datetime objects, convert missing values (NaN, None, etc) into NaT, and convert unparseable timestamp values into NaT. This 3rd case is what made our NA value count go from 884 to 23028 post-function application, meaning that there were many cases where the original timestamp values were not NaN but were converted to NaT. In other words, many of the original timestamp values may not be compatible with Pandas' datetime parsing rules.

To better handle these cases, we decided to use a format='mixed' parameter. This lets Pandas infer the format of each value individually, which is useful because our dataset contains multiple timestamp formats.

Furthermore, to maintain the original timestamp values for comparison, we created a copy of the column using .copy() before parsing. This allowed us to distinguish between values that were already missing and values that failed to parse during conversion. We then updated the rows_affected calculation to count only values that were originally non-missing but became NaT after parsing, giving us a more accurate measure of parsing failures.

In [17]:
# Parse timestamp function by converting to date time format

def parse_timestamp(column_name):
  original = df[column_name].copy()

  standardized = pd.to_datetime(original, errors='coerce', format='mixed')
  rows_affected = (original.notna() & standardized.isna()).sum()
  df[column_name] = standardized

  return df, rows_affected

df, rows_affected = parse_timestamp('timestamp')

log(
    'Data cleaning',
    'timestamp: Parse timestamp function by converting to date time format',
    rows_affected
)

[Data cleaning] timestamp: Parse timestamp function by converting to date time format (0 row(s))

In [18]:
# Post-function analysis

print('Post-parse_timestamp()\n')
print('Updated datatype:', df['timestamp'].dtype)
print('NaT count:', df['timestamp'].isna().sum())
print('Unique values:\n', df['timestamp'].unique())

Post-parse_timestamp()

Updated datatype: datetime64[ns]
NaT count: 884
Unique values:
 <DatetimeArray>
['2024-09-24 09:48:13', '2024-09-13 20:30:20', '2024-09-17 10:06:00',
 '2024-09-11 06:29:08', '2024-09-26 15:59:42', '2024-09-23 10:32:34',
 '2024-09-26 09:26:00', '2024-09-22 14:47:00', '2024-09-08 16:40:14',
 '2024-09-24 20:03:00',
 ...
 '2024-09-24 17:10:49', '2024-09-19 13:59:16', '2024-09-07 22:22:26',
 '2024-09-11 20:40:00', '2024-09-05 13:13:40', '2024-09-04 17:32:37',
 '2024-09-03 18:28:07', '2024-09-26 08:47:08', '2024-09-16 16:39:00',
 '2024-09-25 17:08:35']
Length: 23418, dtype: datetime64[ns]

In [19]:
# SKU analysis

# SKU counts
print("Missing SKUs:", df['sku'].isna().sum())
print("Leading and trailing whitespace count:", df['sku'].astype('string').ne(df['sku'].astype('string').str.strip()).sum())
print("Lowercase SKUs count:", df['sku'].dropna().ne(df['sku'].dropna().str.upper()).sum())
print("Empty SKUs:", df['sku'].eq('').sum(), '\n')

# Duplicate SKUs
print("Total rows:", len(df))
print("Unique SKUs:", df['sku'].nunique())
print("Repeated SKU rows:", df['sku'].duplicated().sum(), '\n')
# Repeated SKU rows are not inherently bad, but SKUs are repeated across transactions
# and all of the 45 unique SKUs are associated with multiple product names

# Find the SKUs that are mapped to multiple product names
sku_product_counts = df.groupby('sku')['product_name'].nunique()
inconsistent_skus = sku_product_counts[sku_product_counts > 1]
print("SKUs mapped to multiple product names:", len(inconsistent_skus))
print(inconsistent_skus)

Missing SKUs: 0
Leading and trailing whitespace count: 0
Lowercase SKUs count: 0
Empty SKUs: 0

Total rows: 25532
Unique SKUs: 45
Repeated SKU rows: 25487

SKUs mapped to multiple product names: 45
sku
BABYFORMULA      2
BAT-AA4          3
BATT-100         3
BATT_AA_4PK      3
BEER-24          3
BFORM-01         2
BG-MONO          3
BREAD-WH         2
CANDLE-EMRG      3
CARDS-01         2
CHIPS-VP         2
CHIPVARIETY      2
CHRG-PORT        3
CNDL-EM          3
CNSOUP-01        2
DIAP-S3          3
DIAPERS-3        3
FAID-01          2
FIRSTAID-KIT     2
FLASH-01         3
GAME-MONO        3
HDTARP-01        3
LED-FLASH        3
LTBEER24         3
MONOPOLY-01      3
PAPERTOWEL6      3
PB-16            2
PLAYCARD-STD     2
PNUTBTR-16       2
POPTART-STRAW    4
PORTCHARGER      3
PT-12            4
PTOWEL-6         3
PT_STRAWBERRY    4
ROKU-STD         3
SKU#459812       4
SOUP-CAN         2
STREAM-01        3
TARP-HD          3
TOILETPAPER12    3
TP-12            3
WATER24PK        3
WHITEBREAD       2
WTR-24           3
WTR_24PK         3
Name: product_name, dtype: int64

In [20]:
# Find SKUs associated with multiple product names
sku_product_counts = df.groupby('sku')['product_name'].nunique()
inconsistent_skus = sku_product_counts[sku_product_counts > 1]

# Inspect the conflicting mappings
print(df[df['sku'].isin(inconsistent_skus.index)][['sku', 'product_name', 'category']].drop_duplicates().sort_values('sku').to_string(index=False))

          sku             product_name              category
  BABYFORMULA             Baby Formula         Baby Products
  BABYFORMULA           Infant Formula         Baby Products
  BABYFORMULA           Infant Formula                  Baby
  BABYFORMULA             Baby Formula                  Baby
      BAT-AA4         Batteries Aa 4Pk             Emergency
      BAT-AA4      Aa Batteries 4-Pack    Emergency Supplies
      BAT-AA4         Batteries Aa 4Pk    Emergency Supplies
      BAT-AA4    Aa Batteries (4-Pack)             Emergency
      BAT-AA4    Aa Batteries (4-Pack)    Emergency Supplies
      BAT-AA4      Aa Batteries 4-Pack             Emergency
     BATT-100         Batteries Aa 4Pk    Emergency Supplies
     BATT-100         Batteries Aa 4Pk             Emergency
     BATT-100      Aa Batteries 4-Pack             Emergency
     BATT-100    Aa Batteries (4-Pack)    Emergency Supplies
     BATT-100    Aa Batteries (4-Pack)             Emergency
     BATT-100      Aa Batteries 4-Pack    Emergency Supplies
  BATT_AA_4PK         Batteries Aa 4Pk    Emergency Supplies
  BATT_AA_4PK    Aa Batteries (4-Pack)    Emergency Supplies
  BATT_AA_4PK         Batteries Aa 4Pk             Emergency
  BATT_AA_4PK    Aa Batteries (4-Pack)             Emergency
  BATT_AA_4PK      Aa Batteries 4-Pack             Emergency
  BATT_AA_4PK      Aa Batteries 4-Pack    Emergency Supplies
      BEER-24     Light Beer (24-Pack)   Alcoholic Beverages
      BEER-24          Beer Light 24Pk   Alcoholic Beverages
      BEER-24          Light Beer 24Pk               Alcohol
      BEER-24     Light Beer (24-Pack)               Alcohol
      BEER-24          Light Beer 24Pk   Alcoholic Beverages
      BEER-24          Beer Light 24Pk               Alcohol
     BFORM-01             Baby Formula         Baby Products
     BFORM-01             Baby Formula                  Baby
     BFORM-01           Infant Formula         Baby Products
     BFORM-01           Infant Formula                  Baby
      BG-MONO                 Monopoly         Entertainment
      BG-MONO                 Monopoly Games & Entertainment
      BG-MONO    Board Game - Monopoly         Entertainment
      BG-MONO      Monopoly Board Game         Entertainment
      BG-MONO      Monopoly Board Game Games & Entertainment
      BG-MONO    Board Game - Monopoly Games & Entertainment
     BREAD-WH            Bread - White             Groceries
     BREAD-WH              White Bread               Grocery
     BREAD-WH              White Bread             Groceries
     BREAD-WH            Bread - White               Grocery
  CANDLE-EMRG        Emergency Candles             Emergency
  CANDLE-EMRG      Candles (Emergency)    Emergency Supplies
  CANDLE-EMRG      Candles (Emergency)             Emergency
  CANDLE-EMRG        Emergency Candles    Emergency Supplies
  CANDLE-EMRG      Candles - Emergency             Emergency
  CANDLE-EMRG      Candles - Emergency    Emergency Supplies
     CARDS-01            Playing Cards Games & Entertainment
     CARDS-01   Standard Playing Cards Games & Entertainment
     CARDS-01            Playing Cards         Entertainment
     CARDS-01   Standard Playing Cards         Entertainment
     CHIPS-VP     Variety Pack - Chips                Snacks
     CHIPS-VP       Chips Variety Pack                Snacks
  CHIPVARIETY     Variety Pack - Chips                Snacks
  CHIPVARIETY       Chips Variety Pack                Snacks
    CHRG-PORT Phone Charger - Portable           Electronics
    CHRG-PORT   Portable Phone Charger           Electronics
    CHRG-PORT         Portable Charger           Electronics
      CNDL-EM      Candles (Emergency)             Emergency
      CNDL-EM      Candles (Emergency)    Emergency Supplies
      CNDL-EM        Emergency Candles    Emergency Supplies
      CNDL-EM        Emergency Candles             Emergency
      CNDL-EM      Candles - Emergency             Emergency
      CNDL-EM      Candles - Emergency    Emergency Supplies
    CNSOUP-01              Canned Soup               Grocery
    CNSOUP-01              Canned Soup             Groceries
    CNSOUP-01            Soup - Canned               Grocery
    CNSOUP-01            Soup - Canned             Groceries
      DIAP-S3           Diapers Size 3                  Baby
      DIAP-S3             Diapers Sz 3                  Baby
      DIAP-S3           Diapers Size 3         Baby Products
      DIAP-S3    Baby Diapers - Size 3                  Baby
      DIAP-S3    Baby Diapers - Size 3         Baby Products
      DIAP-S3             Diapers Sz 3         Baby Products
    DIAPERS-3    Baby Diapers - Size 3                  Baby
    DIAPERS-3             Diapers Sz 3         Baby Products
    DIAPERS-3    Baby Diapers - Size 3         Baby Products
    DIAPERS-3           Diapers Size 3                  Baby
    DIAPERS-3             Diapers Sz 3                  Baby
    DIAPERS-3           Diapers Size 3         Baby Products
      FAID-01            First-Aid Kit                Health
      FAID-01            First-Aid Kit     Health & Wellness
      FAID-01            First Aid Kit                Health
      FAID-01            First Aid Kit     Health & Wellness
 FIRSTAID-KIT            First-Aid Kit                Health
 FIRSTAID-KIT            First-Aid Kit     Health & Wellness
 FIRSTAID-KIT            First Aid Kit                Health
 FIRSTAID-KIT            First Aid Kit     Health & Wellness
     FLASH-01           Flashlight Led             Emergency
     FLASH-01         Flashlight - Led    Emergency Supplies
     FLASH-01           Led Flashlight    Emergency Supplies
     FLASH-01         Flashlight - Led             Emergency
     FLASH-01           Flashlight Led    Emergency Supplies
     FLASH-01           Led Flashlight             Emergency
    GAME-MONO                 Monopoly         Entertainment
    GAME-MONO      Monopoly Board Game         Entertainment
    GAME-MONO    Board Game - Monopoly Games & Entertainment
    GAME-MONO      Monopoly Board Game Games & Entertainment
    GAME-MONO                 Monopoly Games & Entertainment
    GAME-MONO    Board Game - Monopoly         Entertainment
    HDTARP-01          Heavy Duty Tarp             Emergency
    HDTARP-01                  Hd Tarp             Emergency
    HDTARP-01        Tarp - Heavy Duty    Emergency Supplies
    HDTARP-01                  Hd Tarp    Emergency Supplies
    HDTARP-01          Heavy Duty Tarp    Emergency Supplies
    HDTARP-01        Tarp - Heavy Duty             Emergency
    LED-FLASH         Flashlight - Led             Emergency
    LED-FLASH           Led Flashlight             Emergency
    LED-FLASH           Flashlight Led             Emergency
    LED-FLASH         Flashlight - Led    Emergency Supplies
    LED-FLASH           Led Flashlight    Emergency Supplies
    LED-FLASH           Flashlight Led    Emergency Supplies
     LTBEER24          Light Beer 24Pk               Alcohol
     LTBEER24          Beer Light 24Pk               Alcohol
     LTBEER24          Beer Light 24Pk   Alcoholic Beverages
     LTBEER24     Light Beer (24-Pack)   Alcoholic Beverages
     LTBEER24     Light Beer (24-Pack)               Alcohol
     LTBEER24          Light Beer 24Pk   Alcoholic Beverages
  MONOPOLY-01                 Monopoly         Entertainment
  MONOPOLY-01    Board Game - Monopoly         Entertainment
  MONOPOLY-01      Monopoly Board Game         Entertainment
  MONOPOLY-01                 Monopoly Games & Entertainment
  MONOPOLY-01      Monopoly Board Game Games & Entertainment
  MONOPOLY-01    Board Game - Monopoly Games & Entertainment
  PAPERTOWEL6             Paper Towels  Household Essentials
  PAPERTOWEL6             Paper Towels             Household
  PAPERTOWEL6      Paper Towels 6-Roll             Household
  PAPERTOWEL6         Paper Towels 6Pk             Household
  PAPERTOWEL6         Paper Towels 6Pk  Household Essentials
  PAPERTOWEL6      Paper Towels 6-Roll  Household Essentials
        PB-16            Peanut Butter               Grocery
        PB-16       Peanut Butter 16Oz               Grocery
        PB-16            Peanut Butter             Groceries
        PB-16       Peanut Butter 16Oz             Groceries
 PLAYCARD-STD            Playing Cards         Entertainment
 PLAYCARD-STD   Standard Playing Cards         Entertainment
 PLAYCARD-STD   Standard Playing Cards Games & Entertainment
 PLAYCARD-STD            Playing Cards Games & Entertainment
   PNUTBTR-16            Peanut Butter             Groceries
   PNUTBTR-16            Peanut Butter               Grocery
   PNUTBTR-16       Peanut Butter 16Oz             Groceries
   PNUTBTR-16       Peanut Butter 16Oz               Grocery
POPTART-STRAW     Pop-Tarts Strawberry       Breakfast Foods
POPTART-STRAW      Strawberry Pop-Tart             Breakfast
POPTART-STRAW      Strawberry Pop-Tart       Breakfast Foods
POPTART-STRAW   Pop Tarts - Strawberry             Breakfast
POPTART-STRAW   Pop Tarts - Strawberry       Breakfast Foods
POPTART-STRAW     Pop-Tarts Strawberry             Breakfast
POPTART-STRAW       Poptart-Strawberry             Breakfast
POPTART-STRAW       Poptart-Strawberry       Breakfast Foods
  PORTCHARGER         Portable Charger           Electronics
  PORTCHARGER Phone Charger - Portable           Electronics
  PORTCHARGER   Portable Phone Charger           Electronics
        PT-12      Strawberry Pop-Tart             Breakfast
        PT-12   Pop Tarts - Strawberry       Breakfast Foods
        PT-12     Pop-Tarts Strawberry       Breakfast Foods
        PT-12   Pop Tarts - Strawberry             Breakfast
        PT-12       Poptart-Strawberry       Breakfast Foods
        PT-12       Poptart-Strawberry             Breakfast
        PT-12     Pop-Tarts Strawberry             Breakfast
        PT-12      Strawberry Pop-Tart       Breakfast Foods
     PTOWEL-6             Paper Towels             Household
     PTOWEL-6         Paper Towels 6Pk  Household Essentials
     PTOWEL-6         Paper Towels 6Pk             Household
     PTOWEL-6      Paper Towels 6-Roll             Household
     PTOWEL-6      Paper Towels 6-Roll  Household Essentials
     PTOWEL-6             Paper Towels  Household Essentials
PT_STRAWBERRY   Pop Tarts - Strawberry       Breakfast Foods
PT_STRAWBERRY      Strawberry Pop-Tart       Breakfast Foods
PT_STRAWBERRY       Poptart-Strawberry             Breakfast
PT_STRAWBERRY       Poptart-Strawberry       Breakfast Foods
PT_STRAWBERRY      Strawberry Pop-Tart             Breakfast
PT_STRAWBERRY     Pop-Tarts Strawberry             Breakfast
PT_STRAWBERRY     Pop-Tarts Strawberry       Breakfast Foods
PT_STRAWBERRY   Pop Tarts - Strawberry             Breakfast
     ROKU-STD         Streaming Device           Electronics
     ROKU-STD          Streaming Stick           Electronics
     ROKU-STD     Roku Streaming Stick           Electronics
   SKU#459812       Poptart-Strawberry             Breakfast
   SKU#459812      Strawberry Pop-Tart       Breakfast Foods
   SKU#459812   Pop Tarts - Strawberry       Breakfast Foods
   SKU#459812     Pop-Tarts Strawberry       Breakfast Foods
   SKU#459812   Pop Tarts - Strawberry             Breakfast
   SKU#459812      Strawberry Pop-Tart             Breakfast
   SKU#459812       Poptart-Strawberry       Breakfast Foods
   SKU#459812     Pop-Tarts Strawberry             Breakfast
     SOUP-CAN            Soup - Canned             Groceries
     SOUP-CAN              Canned Soup             Groceries
     SOUP-CAN            Soup - Canned               Grocery
     SOUP-CAN              Canned Soup               Grocery
    STREAM-01     Roku Streaming Stick           Electronics
    STREAM-01         Streaming Device           Electronics
    STREAM-01          Streaming Stick           Electronics
      TARP-HD        Tarp - Heavy Duty             Emergency
      TARP-HD          Heavy Duty Tarp             Emergency
      TARP-HD                  Hd Tarp    Emergency Supplies
      TARP-HD          Heavy Duty Tarp    Emergency Supplies
      TARP-HD        Tarp - Heavy Duty    Emergency Supplies
      TARP-HD                  Hd Tarp             Emergency
TOILETPAPER12               Tp 12 Pack             Household
TOILETPAPER12     Toilet Paper 12-Roll             Household
TOILETPAPER12        Toilet Paper 12Pk  Household Essentials
TOILETPAPER12        Toilet Paper 12Pk             Household
TOILETPAPER12               Tp 12 Pack  Household Essentials
TOILETPAPER12     Toilet Paper 12-Roll  Household Essentials
        TP-12     Toilet Paper 12-Roll             Household
        TP-12        Toilet Paper 12Pk             Household
        TP-12               Tp 12 Pack             Household
        TP-12        Toilet Paper 12Pk  Household Essentials
        TP-12     Toilet Paper 12-Roll  Household Essentials
        TP-12               Tp 12 Pack  Household Essentials
    WATER24PK          Water - 24 Pack             Emergency
    WATER24PK          Water - 24 Pack    Emergency Supplies
    WATER24PK       Bottled Water 24Pk             Emergency
    WATER24PK       Bottled Water 24Pk    Emergency Supplies
    WATER24PK    Bottled Water 24-Pack             Emergency
    WATER24PK    Bottled Water 24-Pack    Emergency Supplies
   WHITEBREAD              White Bread               Grocery
   WHITEBREAD            Bread - White             Groceries
   WHITEBREAD            Bread - White               Grocery
   WHITEBREAD              White Bread             Groceries
       WTR-24       Bottled Water 24Pk             Emergency
       WTR-24          Water - 24 Pack    Emergency Supplies
       WTR-24    Bottled Water 24-Pack    Emergency Supplies
       WTR-24          Water - 24 Pack             Emergency
       WTR-24    Bottled Water 24-Pack             Emergency
       WTR-24       Bottled Water 24Pk    Emergency Supplies
     WTR_24PK       Bottled Water 24Pk             Emergency
     WTR_24PK    Bottled Water 24-Pack             Emergency
     WTR_24PK          Water - 24 Pack             Emergency
     WTR_24PK    Bottled Water 24-Pack    Emergency Supplies
     WTR_24PK          Water - 24 Pack    Emergency Supplies
     WTR_24PK       Bottled Water 24Pk    Emergency Supplies

**Clean product_name**

To figure out which product_name we wanted to use, we decided to look up the various product names online to see what the most standardized way of addressing these columns were. For instance, for the beer, there were two different ways of saying it - "Light Beer" and "Beer Light". "Light Beer" seemed to be the more standardized way of addressing this product. Moreover, we put descriptors of size, pack size, and fluid size in parenthesis.

In [21]:
# Find product names that contain a keyword, ignoring capitalization and missing values

# Returns the SKUs, names, and categories related to the description
def clean_product_name(description):
  product = df.loc[df['product_name'].str.lower().str.contains(description.lower(), na=False)]

  # Number of rows
  # print(f'There are {len(product)} rows that look like {description} products.\n')

  # List SKUs, names, and categories
  return product[['sku', 'product_name', 'category']].drop_duplicates()

**SKU mapping to one canonical SKU, product name mapping, and category mapping**

In [22]:
## Baby Formula products
print('Formula Information Before Cleaning:\n', clean_product_name('Formula'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'BFORM-01': 'BABYFORMULA'
}

# Map product names to one canonical name
product_name_mapping = {
    'Infant Formula': 'Baby Formula'
}

# Map category names to one canonical name
category_mapping = {
    'Baby': 'Baby Products'
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Formula Information After Cleaning:\n', clean_product_name('Formula'))

Formula Information Before Cleaning:
               sku    product_name       category
30       BFORM-01  Infant Formula  Baby Products
49    BABYFORMULA  Infant Formula  Baby Products
70    BABYFORMULA  Infant Formula           Baby
108   BABYFORMULA    Baby Formula  Baby Products
112      BFORM-01    Baby Formula           Baby
133   BABYFORMULA    Baby Formula           Baby
235      BFORM-01  Infant Formula           Baby
1128     BFORM-01    Baby Formula  Baby Products

Formula Information After Cleaning:
             sku  product_name       category
30  BABYFORMULA  Baby Formula  Baby Products

Decision: For some of the sku values, it has the number 100 included in it. However, the product_name says 4-pack. Maybe the person inputting the data meant to say that it is a 4-pack because it is more unrealistic to be selling an 100-pack of Aa batteries at Walmart. We decided to treat these instances as a 4-pack of batteries.

In [23]:
## Aa Batteries (4-Pack) products
print('Batteries Information Before Cleaning:\n', clean_product_name('Batteries'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'BATT_AA_4PK': 'AA_BATT_4PK',
    'BATT-AA4': 'AA_BATT_4PK',
    'BATT-100': 'AA_BATT_4PK',
    'BAT-AA4': 'AA_BATT_4PK'
}

# Map product names to one canonical name
product_name_mapping = {
    'Aa Batteries (4-Pack)': 'Batteries AA 4-Pack',
    'Aa Batteries 4-Pack': 'Batteries AA 4-Pack',
    'Batteries Aa 4Pk': 'Batteries AA 4-Pack'
}

# Map categories to one canonical category
category_mapping = {
    'Emergency': 'Emergency Supplies'
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Batteries Information After Cleaning:\n', clean_product_name('Batteries'))

Batteries Information Before Cleaning:
               sku           product_name            category
28    BATT_AA_4PK  Aa Batteries (4-Pack)           Emergency
38       BATT-100       Batteries Aa 4Pk  Emergency Supplies
83       BATT-100       Batteries Aa 4Pk           Emergency
85        BAT-AA4  Aa Batteries (4-Pack)  Emergency Supplies
93    BATT_AA_4PK    Aa Batteries 4-Pack           Emergency
96        BAT-AA4    Aa Batteries 4-Pack           Emergency
105   BATT_AA_4PK       Batteries Aa 4Pk           Emergency
147       BAT-AA4       Batteries Aa 4Pk  Emergency Supplies
154   BATT_AA_4PK  Aa Batteries (4-Pack)  Emergency Supplies
176      BATT-100  Aa Batteries (4-Pack)           Emergency
192      BATT-100    Aa Batteries 4-Pack           Emergency
250       BAT-AA4       Batteries Aa 4Pk           Emergency
328      BATT-100    Aa Batteries 4-Pack  Emergency Supplies
432   BATT_AA_4PK       Batteries Aa 4Pk  Emergency Supplies
434       BAT-AA4  Aa Batteries (4-Pack)           Emergency
784      BATT-100  Aa Batteries (4-Pack)  Emergency Supplies
1025      BAT-AA4    Aa Batteries 4-Pack  Emergency Supplies
2408  BATT_AA_4PK    Aa Batteries 4-Pack  Emergency Supplies

Batteries Information After Cleaning:
             sku         product_name            category
28  AA_BATT_4PK  Batteries AA 4-Pack  Emergency Supplies

In [24]:
## Light Beer (24-Pack) products
print('Beer Information Before Cleaning:\n', clean_product_name('Beer'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'LTBEER24': 'LT_BEER_24PK',
    'BEER-24': 'LT_BEER_24PK'
}

# Map product names to one canonical name
product_name_mapping = {
    'Light Beer 24Pk': 'Light Beer (24-Pack)',
    'Light Beer (24-Pack)': 'Light Beer (24-Pack)',
    'Beer Light 24Pk': 'Light Beer (24-Pack)'
}

# Map categories to one canonical category
category_mapping = {
    'Alcohol': 'Alcoholic Beverages'
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Beer Information After Cleaning:\n', clean_product_name('Beer'))

Beer Information Before Cleaning:
           sku          product_name             category
4     BEER-24       Light Beer 24Pk  Alcoholic Beverages
17    BEER-24       Light Beer 24Pk              Alcohol
22   LTBEER24       Light Beer 24Pk              Alcohol
67    BEER-24  Light Beer (24-Pack)  Alcoholic Beverages
69    BEER-24       Beer Light 24Pk  Alcoholic Beverages
80   LTBEER24  Light Beer (24-Pack)  Alcoholic Beverages
97    BEER-24       Beer Light 24Pk              Alcohol
116  LTBEER24       Beer Light 24Pk              Alcohol
164  LTBEER24  Light Beer (24-Pack)              Alcohol
179  LTBEER24       Beer Light 24Pk  Alcoholic Beverages
203   BEER-24  Light Beer (24-Pack)              Alcohol
416  LTBEER24       Light Beer 24Pk  Alcoholic Beverages

Beer Information After Cleaning:
             sku          product_name             category
4  LT_BEER_24PK  Light Beer (24-Pack)  Alcoholic Beverages

In [25]:
## Monopoly Board Game products
print('Monopoly Information Before Cleaning:\n', clean_product_name('Monopoly'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'BG-MONO': 'BG_MONOPOLY',
    'MONOPOLY-01': 'BG_MONOPOLY',
    'GAME-MONO': 'BG_MONOPOLY'
}

# Map product names to one canonical name
product_name_mapping = {
    'Board Game - Monopoly': 'Monopoly Board Game',
    'Monopoly': 'Monopoly Board Game'
}

# Map categories to one canonical category
category_mapping = {
    'Entertainment': 'Games & Entertainment'
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Monopoly Information After Cleaning:\n', clean_product_name('Beer'))

Monopoly Information Before Cleaning:
               sku           product_name               category
65        BG-MONO    Monopoly Board Game          Entertainment
76    MONOPOLY-01  Board Game - Monopoly          Entertainment
125   MONOPOLY-01    Monopoly Board Game          Entertainment
157     GAME-MONO    Monopoly Board Game          Entertainment
171     GAME-MONO  Board Game - Monopoly          Entertainment
292   MONOPOLY-01               Monopoly          Entertainment
350       BG-MONO    Monopoly Board Game  Games & Entertainment
385       BG-MONO               Monopoly          Entertainment
429       BG-MONO  Board Game - Monopoly          Entertainment
540   MONOPOLY-01    Monopoly Board Game  Games & Entertainment
612     GAME-MONO               Monopoly  Games & Entertainment
624     GAME-MONO    Monopoly Board Game  Games & Entertainment
637     GAME-MONO  Board Game - Monopoly  Games & Entertainment
699     GAME-MONO               Monopoly          Entertainment
754   MONOPOLY-01               Monopoly  Games & Entertainment
941       BG-MONO               Monopoly  Games & Entertainment
1342  MONOPOLY-01  Board Game - Monopoly  Games & Entertainment
1640      BG-MONO  Board Game - Monopoly  Games & Entertainment

Monopoly Information After Cleaning:
             sku          product_name             category
4  LT_BEER_24PK  Light Beer (24-Pack)  Alcoholic Beverages

In [26]:
## White Bread products
print('Bread Information Before Cleaning:\n', clean_product_name('Bread'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'WHITEBREAD': 'WH_BREAD',
    'BREAD-WH': 'WH_BREAD'
}

# Map product names to one canonical name
product_name_mapping = {
    'Bread - White': 'White Bread'
}

# Map categories to one canonical category
category_mapping = {
    'Grocery': 'Groceries'
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Bread Information After Cleaning:\n', clean_product_name('Bread'))

Bread Information Before Cleaning:
             sku   product_name   category
15   WHITEBREAD  Bread - White    Grocery
58   WHITEBREAD    White Bread    Grocery
128    BREAD-WH    White Bread    Grocery
243    BREAD-WH    White Bread  Groceries
244  WHITEBREAD    White Bread  Groceries
254    BREAD-WH  Bread - White    Grocery
529    BREAD-WH  Bread - White  Groceries
851  WHITEBREAD  Bread - White  Groceries

Bread Information After Cleaning:
          sku product_name   category
15  WH_BREAD  White Bread  Groceries

In [27]:
## Emergency Candles products

print('Candles Information Before Cleaning:\n', clean_product_name('Candles'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'CANDLE-EMRG': 'EM_CNDL',
    'CNDL-EM': 'EM_CNDL'
}

# Map product names to one canonical name
product_name_mapping = {
    'Candles (Emergency)': 'Emergency Candles',
    'Candles - Emergency': 'Emergency Candles'
}

# Do not need to map categories to one canonical name

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Candles Information After Cleaning:\n', clean_product_name('Candles'))

Candles Information Before Cleaning:
              sku         product_name            category
9    CANDLE-EMRG    Emergency Candles  Emergency Supplies
40       CNDL-EM    Emergency Candles  Emergency Supplies
72   CANDLE-EMRG  Candles (Emergency)  Emergency Supplies
74       CNDL-EM  Candles - Emergency  Emergency Supplies
135      CNDL-EM  Candles (Emergency)  Emergency Supplies
265  CANDLE-EMRG  Candles - Emergency  Emergency Supplies

Candles Information After Cleaning:
        sku       product_name            category
9  EM_CNDL  Emergency Candles  Emergency Supplies

In [28]:
## Standard Playing Cards product

print('Card Information Before Cleaning:\n', clean_product_name('Cards'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'CARDS-01': 'STD_PLAYCARD',
    'PLAYCARD-STD': 'STD_PLAYCARD'
}

# Map product names to one canonical name
product_name_mapping = {
    'Playing Cards': 'Standard Playing Cards'
}

# Do not need to map categories to one canonical name

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Card Information After Cleaning:\n', clean_product_name('Cards'))

Card Information Before Cleaning:
               sku            product_name               category
10       CARDS-01           Playing Cards  Games & Entertainment
42       CARDS-01  Standard Playing Cards  Games & Entertainment
61   PLAYCARD-STD           Playing Cards  Games & Entertainment
426  PLAYCARD-STD  Standard Playing Cards  Games & Entertainment

Card Information After Cleaning:
              sku            product_name               category
10  STD_PLAYCARD  Standard Playing Cards  Games & Entertainment

In [29]:
## Chips Variety Pack product

print('Chips Information Before Cleaning:\n', clean_product_name('Chips'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'CHIPVARIETY': 'VP_CHIPS',
    'CHIPS-VP': 'VP_CHIPS'
}

# Map product names to one canonical name
product_name_mapping = {
    'Variety Pack - Chips': 'Chips Variety Pack'
}

# Do not need to map categories to one canonical name

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Chips Information After Cleaning:\n', clean_product_name('Chips'))

Chips Information Before Cleaning:
              sku          product_name category
5    CHIPVARIETY    Chips Variety Pack   Snacks
12      CHIPS-VP    Chips Variety Pack   Snacks
71      CHIPS-VP  Variety Pack - Chips   Snacks
389  CHIPVARIETY  Variety Pack - Chips   Snacks

Chips Information After Cleaning:
         sku        product_name category
5  VP_CHIPS  Chips Variety Pack   Snacks

In [30]:
## Portable Phone Charger product

print('Charger Information Before Cleaning:\n', clean_product_name('Charger'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'PORTCHARGER': 'PORT_CHRG',
    'CHRG-PORT': 'PORT_CHRG'
}

# Map product names to one canonical name
product_name_mapping = {
    'Portable Charger': 'Portable Phone Charger',
    'Phone Charger - Portable': 'Portable Phone Charger'
}

# Do not need to map categories to one canonical name

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Charger Information After Cleaning:\n', clean_product_name('Charger'))

Charger Information Before Cleaning:
              sku              product_name     category
16   PORTCHARGER    Portable Phone Charger  Electronics
50   PORTCHARGER          Portable Charger  Electronics
64     CHRG-PORT  Phone Charger - Portable  Electronics
149  PORTCHARGER  Phone Charger - Portable  Electronics
183    CHRG-PORT          Portable Charger  Electronics
248    CHRG-PORT    Portable Phone Charger  Electronics

Charger Information After Cleaning:
           sku            product_name     category
16  PORT_CHRG  Portable Phone Charger  Electronics

In [31]:
## Canned Soup product

print('Soup Information Before Cleaning:\n', clean_product_name('Soup'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'CNSOUP-01': 'CANNED_SOUP',
    'SOUP-CAN': 'CANNED_SOUP'
}

# Map product names to one canonical name
product_name_mapping = {
    'Soup - Canned': 'Canned Soup'
}

# Do not need to map categories to one canonical name

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Soup Information After Cleaning:\n', clean_product_name('Soup'))

Soup Information Before Cleaning:
            sku   product_name   category
1    CNSOUP-01    Canned Soup  Groceries
55    SOUP-CAN    Canned Soup  Groceries
63    SOUP-CAN  Soup - Canned  Groceries
262  CNSOUP-01  Soup - Canned  Groceries

Soup Information After Cleaning:
            sku product_name   category
1  CANNED_SOUP  Canned Soup  Groceries

In [32]:
## Baby Diapers (Size 3) product

print('Diapers Information Before Cleaning:\n', clean_product_name('Diapers'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'DIAP-S3': 'DIAPERS-S3',
    'DIAPERS-3': 'DIAPERS-S3'
}

# Map product names to one canonical name
product_name_mapping = {
    'Diapers Sz 3': 'Baby Diapers (Size 3)',
    'Diapers Size 3': 'Baby Diapers (Size 3)',
    'Baby Diapers - Size 3': 'Baby Diapers (Size 3)'
}

# Do not need to map categories to one canonical name

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Diapers Information After Cleaning:\n', clean_product_name('Diapers'))

Diapers Information Before Cleaning:
            sku           product_name       category
51     DIAP-S3           Diapers Sz 3  Baby Products
53   DIAPERS-3         Diapers Size 3  Baby Products
56   DIAPERS-3           Diapers Sz 3  Baby Products
87     DIAP-S3         Diapers Size 3  Baby Products
94     DIAP-S3  Baby Diapers - Size 3  Baby Products
469  DIAPERS-3  Baby Diapers - Size 3  Baby Products

Diapers Information After Cleaning:
            sku           product_name       category
51  DIAPERS-S3  Baby Diapers (Size 3)  Baby Products

In [33]:
## First Aid Kit product

print('Aid Information Before Cleaning:\n', clean_product_name('Aid'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'FAID-01': 'FIRSTAID-KIT'
}

# Map product names to one canonical name
product_name_mapping = {
    'First-Aid Kit': 'First Aid Kit'
}

# Map categories to one canonical category
category_mapping = {
    'Health': 'Health & Wellness'
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Aid Information After Cleaning:\n', clean_product_name('Aid'))

Aid Information Before Cleaning:
               sku   product_name           category
19   FIRSTAID-KIT  First Aid Kit             Health
110       FAID-01  First Aid Kit             Health
120  FIRSTAID-KIT  First-Aid Kit             Health
178  FIRSTAID-KIT  First-Aid Kit  Health & Wellness
204       FAID-01  First-Aid Kit             Health
285  FIRSTAID-KIT  First Aid Kit  Health & Wellness
312       FAID-01  First-Aid Kit  Health & Wellness
648       FAID-01  First Aid Kit  Health & Wellness

Aid Information After Cleaning:
              sku   product_name           category
19  FIRSTAID-KIT  First Aid Kit  Health & Wellness

In [34]:
## Led Flashlight product

print('Flashlight Information Before Cleaning:\n', clean_product_name('Flashlight'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'FLASH-01': 'LED-FLASH'
}

# Map product names to one canonical name
product_name_mapping = {
    'Flashlight - Led': 'Led Flashlight',
    'Flashlight Led': 'Led Flashlight'
}

# Do not need to map categories to one canonical name


# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Aid Information After Cleaning:\n', clean_product_name('Aid'))

Flashlight Information Before Cleaning:
            sku      product_name            category
23    FLASH-01  Flashlight - Led  Emergency Supplies
43    FLASH-01    Flashlight Led  Emergency Supplies
88   LED-FLASH    Led Flashlight  Emergency Supplies
89   LED-FLASH  Flashlight - Led  Emergency Supplies
231  LED-FLASH    Flashlight Led  Emergency Supplies
269   FLASH-01    Led Flashlight  Emergency Supplies

Aid Information After Cleaning:
              sku   product_name           category
19  FIRSTAID-KIT  First Aid Kit  Health & Wellness

In [35]:
## Heavy Duty Tarp product

print('Tarp Information Before Cleaning:\n', clean_product_name('Tarp'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'TARP-HD': 'HD_TARP',
    'HDTARP-01': 'HD_TARP'
}

# Map product names to one canonical name
product_name_mapping = {
    'Tarp - Heavy Duty': 'Heavy Duty Tarp',
    'Hd Tarp': 'Heavy Duty Tarp'
}

# Do not need to map categories to one canonical name

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Tarp Information After Cleaning:\n', clean_product_name('Tarp'))

Tarp Information Before Cleaning:
            sku       product_name            category
6      TARP-HD  Tarp - Heavy Duty  Emergency Supplies
13   HDTARP-01  Tarp - Heavy Duty  Emergency Supplies
54   HDTARP-01    Heavy Duty Tarp  Emergency Supplies
75   HDTARP-01            Hd Tarp  Emergency Supplies
207    TARP-HD    Heavy Duty Tarp  Emergency Supplies
396    TARP-HD            Hd Tarp  Emergency Supplies

Tarp Information After Cleaning:
        sku     product_name            category
6  HD_TARP  Heavy Duty Tarp  Emergency Supplies

In [36]:
## Paper Towels (6-Pack) product

print('Paper Towels Information Before Cleaning:\n', clean_product_name('Paper Towels'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'PAPERTOWEL6': 'PTOWEL_6PK',
    'PTOWEL-6': 'PTOWEL_6PK'
}

# Map product names to one canonical name
product_name_mapping = {
    'Paper Towels 6Pk': 'Paper Towels (6-Pack)',
    'Paper Towels': 'Paper Towels (6-Pack)',
    'Paper Towels 6-Roll': 'Paper Towels (6-Pack)'
}

# Map categories to one canonical category
category_mapping = {
    'Household': 'Household Essentials'
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Paper Towels Information After Cleaning:\n', clean_product_name('Paper Towels'))

Paper Towels Information Before Cleaning:
              sku         product_name              category
7    PAPERTOWEL6     Paper Towels 6Pk             Household
18      PTOWEL-6         Paper Towels  Household Essentials
24   PAPERTOWEL6         Paper Towels             Household
121  PAPERTOWEL6         Paper Towels  Household Essentials
129  PAPERTOWEL6  Paper Towels 6-Roll             Household
193     PTOWEL-6     Paper Towels 6Pk             Household
232     PTOWEL-6         Paper Towels             Household
352  PAPERTOWEL6     Paper Towels 6Pk  Household Essentials
374     PTOWEL-6  Paper Towels 6-Roll             Household
464     PTOWEL-6  Paper Towels 6-Roll  Household Essentials
604  PAPERTOWEL6  Paper Towels 6-Roll  Household Essentials
628     PTOWEL-6     Paper Towels 6Pk  Household Essentials

Paper Towels Information After Cleaning:
           sku           product_name              category
7  PTOWEL_6PK  Paper Towels (6-Pack)  Household Essentials

In [37]:
## Peanut Butter (16 Oz) product

print('Peanut Butter Information Before Cleaning:\n', clean_product_name('Peanut Butter'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'PNUTBTR-16': 'PB_16OZ',
    'PB-16': 'PB_16OZ'
}

# Map product names to one canonical name
product_name_mapping = {
    'Peanut Butter': 'Peanut Butter (16 Oz)',
    'Peanut Butter 16Oz': 'Peanut Butter (16 Oz)'
}

# Do not need to map categories to one canonical name

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)

print('Peanut Butter Information After Cleaning:\n', clean_product_name('Peanut Butter'))

Peanut Butter Information Before Cleaning:
             sku        product_name   category
0    PNUTBTR-16       Peanut Butter  Groceries
26        PB-16  Peanut Butter 16Oz  Groceries
102       PB-16       Peanut Butter  Groceries
111  PNUTBTR-16  Peanut Butter 16Oz  Groceries

Peanut Butter Information After Cleaning:
        sku           product_name   category
0  PB_16OZ  Peanut Butter (16 Oz)  Groceries

In [38]:
## Strawberry Pop-Tarts (12-Pack) product

print('Pop-Tarts Information Before Cleaning:\n', clean_product_name('Tart'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'PT_STRAWBERRY': 'STAW_PT_12PK',
    'POPTART-STRAW': 'STAW_PT_12PK',
    'SKU#459812': 'STAW_PT_12PK',
    'PT-12': 'STAW_PT_12PK'
}

# Map product names to one canonical name
product_name_mapping = {
    'Pop-Tarts Strawberry': 'Strawberry Pop-Tarts (12-Pack)',
    'Poptart-Strawberry': 'Strawberry Pop-Tarts (12-Pack)',
    'Strawberry Pop-Tart': 'Strawberry Pop-Tarts (12-Pack)',
    'Pop Tarts - Strawberry': 'Strawberry Pop-Tarts (12-Pack)'
}

# Map categories to one canonical category
category_mapping = {
    'Breakfast': 'Breakfast Foods'
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)
df['category'] = df['category'].replace(category_mapping)

print('Pop-Tarts Information After Cleaning:\n', clean_product_name('Tart'))

Pop-Tarts Information Before Cleaning:
                 sku            product_name         category
21    PT_STRAWBERRY    Pop-Tarts Strawberry        Breakfast
27       SKU#459812      Poptart-Strawberry        Breakfast
29    PT_STRAWBERRY     Strawberry Pop-Tart        Breakfast
47            PT-12  Pop Tarts - Strawberry        Breakfast
52    POPTART-STRAW     Strawberry Pop-Tart        Breakfast
123   POPTART-STRAW    Pop-Tarts Strawberry  Breakfast Foods
138           PT-12      Poptart-Strawberry        Breakfast
142      SKU#459812    Pop-Tarts Strawberry        Breakfast
148   PT_STRAWBERRY      Poptart-Strawberry        Breakfast
165   POPTART-STRAW      Poptart-Strawberry  Breakfast Foods
202      SKU#459812     Strawberry Pop-Tart        Breakfast
220   POPTART-STRAW      Poptart-Strawberry        Breakfast
227           PT-12     Strawberry Pop-Tart  Breakfast Foods
242   PT_STRAWBERRY      Poptart-Strawberry  Breakfast Foods
260      SKU#459812    Pop-Tarts Strawberry  Breakfast Foods
264           PT-12    Pop-Tarts Strawberry        Breakfast
297   PT_STRAWBERRY    Pop-Tarts Strawberry  Breakfast Foods
305   POPTART-STRAW    Pop-Tarts Strawberry        Breakfast
315      SKU#459812  Pop Tarts - Strawberry        Breakfast
330   PT_STRAWBERRY  Pop Tarts - Strawberry        Breakfast
334      SKU#459812      Poptart-Strawberry  Breakfast Foods
431   PT_STRAWBERRY     Strawberry Pop-Tart  Breakfast Foods
455   PT_STRAWBERRY  Pop Tarts - Strawberry  Breakfast Foods
600      SKU#459812     Strawberry Pop-Tart  Breakfast Foods
631           PT-12  Pop Tarts - Strawberry  Breakfast Foods
810   POPTART-STRAW     Strawberry Pop-Tart  Breakfast Foods
853   POPTART-STRAW  Pop Tarts - Strawberry        Breakfast
1111  POPTART-STRAW  Pop Tarts - Strawberry  Breakfast Foods
1160          PT-12     Strawberry Pop-Tart        Breakfast
1547          PT-12      Poptart-Strawberry  Breakfast Foods
2027          PT-12    Pop-Tarts Strawberry  Breakfast Foods
2857     SKU#459812  Pop Tarts - Strawberry  Breakfast Foods

Pop-Tarts Information After Cleaning:
              sku                    product_name         category
21  STAW_PT_12PK  Strawberry Pop-Tarts (12-Pack)  Breakfast Foods

In [39]:
## Roku Streaming Stick product

print('Streaming Information Before Cleaning:\n', clean_product_name('Streaming'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'ROKU-STD': 'ROKU_STR',
    'STREAM-01': 'ROKU_STR'
}

# Map product names to one canonical name
product_name_mapping = {
    'Streaming Stick': 'Roku Streaming Stick',
    'Streaming Device': 'Roku Streaming Stick'
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)

print('Streaming Information After Cleaning:\n', clean_product_name('Streaming'))

Streaming Information Before Cleaning:
            sku          product_name     category
3     ROKU-STD  Roku Streaming Stick  Electronics
34   STREAM-01  Roku Streaming Stick  Electronics
37   STREAM-01       Streaming Stick  Electronics
81   STREAM-01      Streaming Device  Electronics
98    ROKU-STD      Streaming Device  Electronics
216   ROKU-STD       Streaming Stick  Electronics

Streaming Information After Cleaning:
         sku          product_name     category
3  ROKU_STR  Roku Streaming Stick  Electronics

In [40]:
## Water Bottle (24-Pack) product

print('Water Information Before Cleaning:\n', clean_product_name('Water'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'WTR-24': 'WATER_24PK',
    'WTR_24PK': 'WATER_24PK',
    'WATER24PK': 'WATER_24PK',
}

# Map product names to one canonical name
product_name_mapping = {
    'Water - 24 Pack': 'Water Bottle (24-Pack)',
    'Bottled Water 24Pk': 'Water Bottle (24-Pack)',
    'Bottled Water 24-Pack': 'Water Bottle (24-Pack)'
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)

print('Water Information After Cleaning:\n', clean_product_name('Water'))

Water Information Before Cleaning:
            sku           product_name            category
31      WTR-24        Water - 24 Pack  Emergency Supplies
62   WATER24PK     Bottled Water 24Pk  Emergency Supplies
155  WATER24PK  Bottled Water 24-Pack  Emergency Supplies
184   WTR_24PK        Water - 24 Pack  Emergency Supplies
189     WTR-24     Bottled Water 24Pk  Emergency Supplies
191     WTR-24  Bottled Water 24-Pack  Emergency Supplies
194   WTR_24PK     Bottled Water 24Pk  Emergency Supplies
240   WTR_24PK  Bottled Water 24-Pack  Emergency Supplies
485  WATER24PK        Water - 24 Pack  Emergency Supplies

Water Information After Cleaning:
            sku            product_name            category
31  WATER_24PK  Water Bottle (24-Pack)  Emergency Supplies

In [50]:
# Toilet Paper (12-Pack) product

print('Toilet Paper Information Before Cleaning:\n', clean_product_name('Toilet Paper'), '\n')

# Map SKUs to one canonical SKU
sku_mapping = {
    'TOILETPAPER12': 'TP_12PK',
    'TP-12': 'TP_12PK'
}

# Map product names to one canonical name
product_name_mapping = {
    'Toilet Paper 12-Roll': 'Toilet Paper (12-Pack)',
    'Toilet Paper 12Pk': 'Toilet Paper (12-Pack)',
    'Tp 12 Pack': 'Toilet Paper (12-Pack)' # Added based on later analysis
}

# Apply mappings
df['sku'] = df['sku'].replace(sku_mapping)
df['product_name'] = df['product_name'].replace(product_name_mapping)

print('Toilet Paper Information After Cleaning:\n', clean_product_name('Toilet Paper'))

Toilet Paper Information Before Cleaning:
        sku            product_name              category
2  TP_12PK  Toilet Paper (12-Pack)  Household Essentials

Toilet Paper Information After Cleaning:
        sku            product_name              category
2  TP_12PK  Toilet Paper (12-Pack)  Household Essentials

In [51]:
# Post-changes analysis

# Duplicate SKUs
print("Total rows:", len(df))
print("Unique SKUs:", df['sku'].nunique())
print("Repeated SKU rows:", df['sku'].duplicated().sum(), '\n')

# Find the SKUs that are mapped to multiple product names
sku_product_counts = df.groupby('sku')['product_name'].nunique()
inconsistent_skus = sku_product_counts[sku_product_counts > 1]
print("SKUs mapped to multiple product names:", len(inconsistent_skus))
print(inconsistent_skus)

Total rows: 25532
Unique SKUs: 20
Repeated SKU rows: 25512

SKUs mapped to multiple product names: 0
Series([], Name: product_name, dtype: int64)

In [55]:
# Check for invalid prices

invalid_prices = df[df['unit_price'].isna() | (df['unit_price'] <= 0)]

print('Number of Invalid Prices:', len(invalid_prices))
print(invalid_prices[['transaction_id', 'sku', 'unit_price']])

Number of Invalid Prices: 0
Empty DataFrame
Columns: [transaction_id, sku, unit_price]
Index: []

In [43]:
# Validate store IDs

In [45]:
# store_id cleaned up so it will join to the store file

### 3 — SKU consolidation progress

**TODO:** how many distinct SKUs did you start with, how many canonical products do you have now, and what is your largest consolidated group? Show the mapping for at least one product family. Pop-Tarts is a good one to start with.

You do not need this finished — you need it started and defensible.

In [46]:
# TODO

### 4 — One working weather API call

**TODO:** show the call and the parsed DataFrame. It must include the retry logic and a `source` column. Say which timezone the weather timestamps are in and how you will line them up with the sales timestamps. If it is not working, paste the actual error and what you have tried.

In [47]:
# TODO

### 5 — One chart

**TODO:** daily order volume across your date range. It does not need to be presentation quality yet, but it does need labeled axes and a title.

Look at it before you submit. Does the shape make sense? An early chart is the fastest way to catch a cleaning bug — if your daily volume has a day at zero or a day at ten times everything else, that is usually your pipeline, not the hurricane.

In [48]:
# TODO

### 6 — Self-check

Fill in what you have and leave the rest. **The required items are the team setup and the charter.** Everything else is progress we want to see, not a pass or fail. The checks are shape checks; they cannot verify your analysis is right, only that you have gotten far enough to have one.

In [49]:
required = {
    'team_setup_complete': check_team(team_setup, quiet=True),   # from the team setup section
    'charter_committed': True,         # TODO: True once CHARTER.md shows in the git log above
}

progress = {
    'rows_after_cleaning': df.shape[0],        # an integer
    'decisions_logged': len(DECISIONS),           # how many entries in your log
    'canonical_products': None,         # distinct products after consolidation
    'weather_api_rows': None,           # rows returned by your API call
    'notebook_runs_clean': True,       # True after Restart and Run All
}

def is_done(value):
    return not (value is None or value is False
                or (isinstance(value, str) and value.startswith('TODO')))

def check(required, progress):
    print('REQUIRED')
    for label, value in required.items():
        print('  PASS' if is_done(value) else '  FAIL', '-', label, '=', value)
    print('PROGRESS (fill in what you have)')
    for label, value in progress.items():
        print('  done' if is_done(value) else '  not yet', '-', label, '=', value)
    ok = all(is_done(v) for v in required.values())
    print()
    print('required items complete:', ok)
    print('progress items done:', sum(is_done(v) for v in progress.values()), 'of', len(progress))
    return ok

check(required, progress)

REQUIRED
  PASS - team_setup_complete = True
  PASS - charter_committed = True
PROGRESS (fill in what you have)
  done - rows_after_cleaning = 25532
  done - decisions_logged = 7
  not yet - canonical_products = None
  not yet - weather_api_rows = None
  done - notebook_runs_clean = True

required items complete: True
progress items done: 3 of 5

True

### 7 — Risk and plan

Two questions, answered concretely.

**a)** What is the single most likely thing to go wrong in the next two weeks? Name a specific technical or team problem, not "running out of time."

**b)** What are you doing about it this week? Name who is doing it and by when.

**Biggest risk:** _..._

**Plan, with an owner and a date:** _..._

### 8 — Where each question stands

**TODO:** mark each of the five questions. These owners must match the question owners table in your charter. Be honest — this is the section I read first.

| Question | Status | Who owns it |
|---|---|---|
| Q1 demand surge | not started / in progress / draft answer | _..._ |
| Q2 SKU consolidation | _..._ | _..._ |
| Q3 weather correlation | _..._ | _..._ |
| Q4 store and geography | _..._ | _..._ |
| Q5 signal or artifact | _..._ | _..._ |

At the end of week 1, "not started" on Q4 and Q5 is expected. "Not started" on all five means come find me on Monday.