# DS2002 · Midterm Checkpoint

**Lab — 2026-10-23 · Fall 2026**  

---

## Lab 09 — Midterm checkpoint, week 1 of 3

**What you submit: the link to your team's main repo. Only that.** One submission per team. Do not upload separate files.

Put this notebook in the repo (the `notebooks/` folder is fine) and push it, so everything we check is in one place.

**You do not have to fill this all out.** It is a checkpoint, not a finished project. Skip any section you have not started and write "not started" next to it. What we must see is:

1. **Your charter**, committed to the repo
2. **Any progress** you have made, with code that ran and output you can point at

Start with the team setup, then work down the same eight things we listed at Monday's kickoff, as far as you have gotten. This is graded on evidence, not on intentions.

The purpose is to catch a stalled team while there is still time to unstall it. If something is not working, say so here plainly. A checkpoint that honestly reports "the API join is not working and here is the error" is worth more than one that claims progress that does not exist, and it gets you help on Monday.

### Team setup

This part is required. Fill it in once for the whole team.

You need:

- Your team name, and every member with a GitHub handle (2 to 4 people)
- A link to your team's **main repo**. This is the one link you submit.
- A link to `CHARTER.md` in that repo, the page on GitHub, not a file on someone's laptop

Nice to have, and also in your charter: this week's notebook owner, your meeting time, and the five worst problems in the data from the profile you ran on Monday. Be specific: "`unit_price` is stored as text and some values start with `$`" beats "prices are messy."

In [1]:
team_setup = {
    'team_name': 'Team Kylie',
    'members': [
        {'name': 'Emma Kee', 'github': 'ekee7'},
        {'name': 'Kylie Sharp', 'github': 'kyliefsharp'},
        {'name': 'Raffaella Alpaca', 'github': 'raffaellaalpaca-ai'},
        {'name': 'Miriam Ahmadd', 'github': 'miriamahmadd'},
    ],
    'repo_url': 'https://github.com/raffaellaalpaca-ai/walmart-hurricane-project',
    'charter_url': 'https://github.com/raffaellaalpaca-ai/walmart-hurricane-project/blob/main/CHARTER.md',
    'notebook_owner_this_week': 'Kylie',
    'meeting_time': 'Wednesday at 10am',
    'five_worst_problems': ['Our schedules do not line up very well', 'We have a lot of midterms', 'We have academic/non-academic commitments', 'We have other projects', 'Data cleaning is time consuming'],
}

def check_team(t, quiet=False):
    def real(v):
        return isinstance(v, str) and v.strip() != '' and not v.startswith('TODO')
    required = {
        'team name': real(t['team_name']),
        '2 to 4 members, each with a name and GitHub handle':
            2 <= len(t['members']) <= 4 and all(real(m['name']) and real(m['github']) for m in t['members']),
        'main repo link': real(t['repo_url']) and t['repo_url'].startswith('https://github.com/'),
        'charter link points at CHARTER.md': real(t['charter_url']) and t['charter_url'].endswith('CHARTER.md'),
    }
    nice = {
        'notebook owner': real(t['notebook_owner_this_week']),
        'meeting time': real(t['meeting_time']),
        'five specific problems': len(t['five_worst_problems']) >= 5 and all(real(p) for p in t['five_worst_problems']),
    }
    if not quiet:
        print('REQUIRED')
        for label, good in required.items():
            print('  PASS' if good else '  FAIL', '-', label)
        print('NICE TO HAVE')
        for label, good in nice.items():
            print('  done' if good else '  not yet', '-', label)
        print()
        print('team setup complete:', all(required.values()))
    return all(required.values())

check_team(team_setup)

REQUIRED
  PASS - team name
  PASS - 2 to 4 members, each with a name and GitHub handle
  PASS - main repo link
  PASS - charter link points at CHARTER.md
NICE TO HAVE
  done - notebook owner
  done - meeting time
  done - five specific problems

team setup complete: True

True

Now show that the charter is actually committed. This is required. Run the next cell and leave its output in the notebook. Point `REPO_PATH` at your local clone of the team repo. If it prints a line like `a1b2c3d Add team charter`, you are done. If it prints "no commits found," the charter is not in the repo yet, so commit it and push before you submit.

In [2]:
!git clone https://github.com/ekee7/walmart-hurricane-project.git

Cloning into 'walmart-hurricane-project'...
remote: Enumerating objects: 91, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 91 (delta 36), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (91/91), 679.96 KiB | 5.48 MiB/s, done.
Resolving deltas: 100% (36/36), done.

In [4]:
import subprocess

REPO_PATH = '/content/walmart-hurricane-project' # Your local clone of the team repo

result = subprocess.run(['git', '-C', REPO_PATH, 'log', '--oneline', '--', 'CHARTER.md'],
                        capture_output=True, text=True)
print(result.stdout.strip() or 'no commits found for CHARTER.md')

b182050 Fixed formatting in CHARTER.md
81e6364 Updated Charter
809052a Updated roles in charter
2a3176e Updated charter with group rules
686fa68 Add project charter outlining goals and responsibilities

In [5]:
import pandas as pd

# Import data set from GitHub
url = 'https://raw.githubusercontent.com/ekee7/walmart-hurricane-project/refs/heads/main/data/walmart_transactions.csv'
df = pd.read_csv(url)

In [6]:
df.head()

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,PEANUT BUTTER,Grocery,1,3.15
1,TXN000759,fl-412,2024-09-13 20:30:20,CNSOUP-01,CANNED SOUP,GROCERY,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,ELECTRONICS,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24pk,Alcoholic Beverages,3,18.82

In [7]:
df.shape

# There are 25562 rows and 8 columns in this dataset

(25562, 8)

### 2 — Your decision log

**TODO:** every cleaning decision, what it did, and how many rows it touched. If your teammates disagree with one of these, note the disagreement — that is useful information, not a problem to hide.

In [8]:
DECISIONS = []

# Function for decision logging
def log(step, decision, rows_affected):
    DECISIONS.append({'step': step, 'decision': decision, 'rows': rows_affected})
    print(f'[{step}] {decision} ({rows_affected} row(s))')

### 1 — Your cleaning pipeline as functions

**TODO:** paste the cleaning code you have written so far. It should be functions, not loose cells, and it should cover at minimum: duplicates, `unit_price` to numeric (it comes in as text, some with a `$`), the negative `quantity` values with your decision applied, `timestamp` parsed, and `store_id` cleaned up so it will join to the store file.

Print the row count before and after. We want to see how many rows your decisions removed.

In [9]:
# Standardize text case to uppercase and strip

def to_uppercase(column_name):
  standardized = df[column_name].str.strip().str.upper()
  rows_affected = df[column_name].ne(standardized).sum() # Count number of rows affected
  df[column_name] = standardized

  return df, rows_affected

# Standardize store_id values by stripping leading/trailing whitespace and converting all characters to uppercase.
# This ensures consistent formatting for matching store IDs when joining with the store dataset.
# EX: FL-710 vs. fl-412 - We want all to be FL-710

df, rows_affected = to_uppercase('store_id')

log(
    'Data cleaning',
    'store_id: standardize text case to uppercase and strip',
    rows_affected
)

df.head()

[Data cleaning] store_id: standardize text case to uppercase and strip (1795 row(s))

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,PEANUT BUTTER,Grocery,1,3.15
1,TXN000759,FL-412,2024-09-13 20:30:20,CNSOUP-01,CANNED SOUP,GROCERY,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,ELECTRONICS,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24pk,Alcoholic Beverages,3,18.82

In [10]:
# Standardize text case to title case and strip

def to_title_case(column_name):
  standardized = df[column_name].str.strip().str.title()
  rows_affected = df[column_name].ne(standardized).sum() # Count number of rows affected
  df[column_name] = standardized

  return df, rows_affected

# Standardize product_name and category column information
# EX: PEANUT BUTTER - We want it to be Peanut Butter

df, rows_affected = to_title_case('product_name')
log('Data cleaning', 'product_name: standardize text case to title case and strip', rows_affected)

df, rows_affected = to_title_case('category')

log(
    'Data cleaning',
    'category: standardize text case to title case and strip',
    rows_affected
)

df.head()

[Data cleaning] product_name: standardize text case to title case and strip (12875 row(s))
[Data cleaning] category: standardize text case to title case and strip (13175 row(s))

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,Peanut Butter,Grocery,1,3.15
1,TXN000759,FL-412,2024-09-13 20:30:20,CNSOUP-01,Canned Soup,Grocery,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,Electronics,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24Pk,Alcoholic Beverages,3,18.82

In [11]:
# Look at the datatypes of the columns
df.dtypes

transaction_id    object
store_id          object
timestamp         object
sku               object
product_name      object
category          object
quantity           int64
unit_price        object
dtype: object

In [12]:
# Update unit_price to be float type, remove $, and strip

def to_float(column_name):
  standardized = df[column_name].str.strip().str.replace('$', '', regex=False).astype(float)
  rows_affected = df[column_name].ne(standardized).sum() # Count number of rows affected
  df[column_name] = standardized

  return df, rows_affected

# unit_price is a String but it should be a float type for future calculations (i.e. summing/etc)
df, rows_affected = to_float('unit_price')

log(
    'Data cleaning',
    'unit_price: update to be float type and remove $',
    rows_affected
)

df.head()

[Data cleaning] unit_price: update to be float type and remove $ (25562 row(s))

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,Peanut Butter,Grocery,1,3.15
1,TXN000759,FL-412,2024-09-13 20:30:20,CNSOUP-01,Canned Soup,Grocery,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,Electronics,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24Pk,Alcoholic Beverages,3,18.82

In [13]:
df['unit_price'].dtype

dtype('float64')

In [14]:
# Duplicate rows function

def drop_duplicate_rows(df):
  rows_affected = df.duplicated().sum() # Count number of rows affected
  df.drop_duplicates(inplace=True)

  return df, rows_affected

# Remove exact duplicate rows because they represent repeated records that could inflate transaction counts and sales totals
# Only rows identical across all columns are removed
# EX: rows that share a transaction_id are not automatically considered duplicates

df, rows_affected = drop_duplicate_rows(df)

log(
    'Data cleaning',
    'Drop duplicate rows',
    rows_affected
)

df.head()

[Data cleaning] Drop duplicate rows (30 row(s))

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,Peanut Butter,Grocery,1,3.15
1,TXN000759,FL-412,2024-09-13 20:30:20,CNSOUP-01,Canned Soup,Grocery,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,Electronics,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24Pk,Alcoholic Beverages,3,18.82

In [15]:
df.shape[0]

25532

In [16]:
# Negative quantity value function

def change_negative_quantities(column_name):
  rows_affected = (df[column_name] < 0).sum() # Count number of rows affected
  df[column_name] = df[column_name].abs()

  return df, rows_affected

# Convert negative quantity values to positive values using abs() so all quantities represent nonnegative units sold
# We decided to make the quantity values positive because negative quantities do not make sense
# Instead of dropping the rows, we decided to view negative quantities as user entry mistakes
df, rows_affected = change_negative_quantities('quantity')

log(
    'Data cleaning',
    'quantity: Changed negative quantity values to positive values',
    rows_affected
)

[Data cleaning] quantity: Changed negative quantity values to positive values (130 row(s))

In [17]:
# Parse timestamp function by converting to date time format

def parse_timestamp(column_name):
  standardized = pd.to_datetime(df[column_name], errors='coerce')
  rows_affected = df[column_name].ne(standardized).sum()
  df[column_name] = standardized

  return df, rows_affected

df, rows_affected = parse_timestamp('timestamp')

log(
    'Data cleaning',
    'timestamp: Parse timestamp function by converting to date time format',
    rows_affected
)

[Data cleaning] timestamp: Parse timestamp function by converting to date time format (23028 row(s))

In [18]:
df['timestamp'].dtype

dtype('<M8[ns]')

In [ ]:
# store_id cleaned up so it will join to the store file

### 3 — SKU consolidation progress

**TODO:** how many distinct SKUs did you start with, how many canonical products do you have now, and what is your largest consolidated group? Show the mapping for at least one product family. Pop-Tarts is a good one to start with.

You do not need this finished — you need it started and defensible.

In [ ]:
# TODO

### 4 — One working weather API call

**TODO:** show the call and the parsed DataFrame. It must include the retry logic and a `source` column. Say which timezone the weather timestamps are in and how you will line them up with the sales timestamps. If it is not working, paste the actual error and what you have tried.

In [19]:
import pandas as pd
import requests
import time

#historical weather API from Open-Meteo
BASE = 'https://archive-api.open-meteo.com/v1/archive'
#temp errors where we should try again
RETRY_STATUSES = {429, 500, 502, 503, 504}

#func to retrieve historical daily weather
def daily_weather(start, end, lat=28.54, lon=-81.38, tries=3):

    #info we send to the API
    params = {
        'latitude': lat,
        'longitude': lon,
        'start_date': start,
        'end_date': end,
        'daily': 'precipitation_sum,windspeed_10m_max',
        'timezone': 'America/New_York'
    }

    #try the request up to 3 times
    for attempt in range(1, tries + 1):
        try:
            response = requests.get(BASE, params=params, timeout=10)
        #handle connection problems
        except (requests.Timeout, requests.ConnectionError):
            if attempt == tries:
                raise
            time.sleep(2 ** attempt)
            continue
        #retry temporary server errors
        if response.status_code in RETRY_STATUSES:
            if attempt == tries:
                response.raise_for_status()
            time.sleep(2 ** attempt)
            continue

        #check for other errors
        response.raise_for_status()

        #convert the API response into a DataFrame
        weather_df = pd.DataFrame(response.json()['daily'])

        #rename time to date
        weather_df = weather_df.rename(columns={'time': 'date'})

        #convert dates into datetime format
        weather_df['date'] = pd.to_datetime(weather_df['date'])

        #identify where the weather data came from
        weather_df['source'] = 'open-meteo'
        return weather_df
#get historical weather for September 2024 in Orlando
weather_df = daily_weather('2024-09-01', '2024-09-30')
print("Weather rows:", len(weather_df))
print("Source:", weather_df['source'].iloc[0])
print("Missing values:")
print(weather_df.isnull().sum())
weather_df.head()

Weather rows: 30
Source: open-meteo
Missing values:
date                 0
precipitation_sum    0
windspeed_10m_max    0
source               0
dtype: int64

        date  precipitation_sum  windspeed_10m_max      source
0 2024-09-01                3.0               18.8  open-meteo
1 2024-09-02               12.4               13.5  open-meteo
2 2024-09-03               24.8               22.8  open-meteo
3 2024-09-04               22.1               15.5  open-meteo
4 2024-09-05               22.7               15.2  open-meteo

We retrieved historical daily weather data from Open-Meteo for Orlando, Florida, covering September 1–30, 2024. The API includes daily precipitation, maximum wind speed, and a source column identifying Open-Meteo.

We requested the weather data using the America/New_York timezone, which represents local time in Orlando. The weather dates represent local calendar days.

Before joining the weather data with Walmart sales, we will verify the timezone of the sales timestamps and convert them to the same local timezone if necessary. Then, we will create a date column from the sales timestamps and perform a left join to preserve all sales records.

We will also check for missing matches, duplicate weather dates, and changes in the number of sales rows after the join.

In [20]:
#check Walmart sales data
print("Sales columns:", df.columns.tolist())
#check sales records we have
print("\nNumber of rows:", len(df))
display(df.head())
#data types
print("\nData types:")
print(df.dtypes)

Sales columns: ['transaction_id', 'store_id', 'timestamp', 'sku', 'product_name', 'category', 'quantity', 'unit_price']

Number of rows: 25532

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24 09:48:13,PNUTBTR-16,Peanut Butter,Grocery,1,3.15
1,TXN000759,FL-412,NaT,CNSOUP-01,Canned Soup,Grocery,1,2.02
2,TXN003338,FL-105,NaT,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,NaT,ROKU-STD,Roku Streaming Stick,Electronics,1,28.59
4,TXN015797,FL-302,NaT,BEER-24,Light Beer 24Pk,Alcoholic Beverages,3,18.82

Data types:
transaction_id            object
store_id                  object
timestamp         datetime64[ns]
sku                       object
product_name              object
category                  object
quantity                   int64
unit_price               float64
dtype: object

### 5 — One chart

**TODO:** daily order volume across your date range. It does not need to be presentation quality yet, but it does need labeled axes and a title.

Look at it before you submit. Does the shape make sense? An early chart is the fastest way to catch a cleaning bug — if your daily volume has a day at zero or a day at ten times everything else, that is usually your pipeline, not the hurricane.

In [ ]:
# TODO

### 6 — Self-check

Fill in what you have and leave the rest. **The required items are the team setup and the charter.** Everything else is progress we want to see, not a pass or fail. The checks are shape checks; they cannot verify your analysis is right, only that you have gotten far enough to have one.

In [ ]:
required = {
    'team_setup_complete': check_team(team_setup, quiet=True),   # from the team setup section
    'charter_committed': True,         # TODO: True once CHARTER.md shows in the git log above
}

progress = {
    'rows_after_cleaning': df.shape[0],        # an integer
    'decisions_logged': len(DECISIONS),           # how many entries in your log
    'canonical_products': None,         # distinct products after consolidation
    'weather_api_rows': None,           # rows returned by your API call
    'notebook_runs_clean': True,       # True after Restart and Run All
}

def is_done(value):
    return not (value is None or value is False
                or (isinstance(value, str) and value.startswith('TODO')))

def check(required, progress):
    print('REQUIRED')
    for label, value in required.items():
        print('  PASS' if is_done(value) else '  FAIL', '-', label, '=', value)
    print('PROGRESS (fill in what you have)')
    for label, value in progress.items():
        print('  done' if is_done(value) else '  not yet', '-', label, '=', value)
    ok = all(is_done(v) for v in required.values())
    print()
    print('required items complete:', ok)
    print('progress items done:', sum(is_done(v) for v in progress.values()), 'of', len(progress))
    return ok

check(required, progress)

REQUIRED
  PASS - team_setup_complete = True
  PASS - charter_committed = True
PROGRESS (fill in what you have)
  done - rows_after_cleaning = 25532
  done - decisions_logged = 7
  not yet - canonical_products = None
  not yet - weather_api_rows = None
  done - notebook_runs_clean = True

required items complete: True
progress items done: 3 of 5

True

### 7 — Risk and plan

Two questions, answered concretely.

**a)** What is the single most likely thing to go wrong in the next two weeks? Name a specific technical or team problem, not "running out of time."

**b)** What are you doing about it this week? Name who is doing it and by when.

**Biggest risk:** _..._

**Plan, with an owner and a date:** _..._

### 8 — Where each question stands

**TODO:** mark each of the five questions. These owners must match the question owners table in your charter. Be honest — this is the section I read first.

| Question | Status | Who owns it |
|---|---|---|
| Q1 demand surge | not started / in progress / draft answer | _..._ |
| Q2 SKU consolidation | _..._ | _..._ |
| Q3 weather correlation | _..._ | _..._ |
| Q4 store and geography | _..._ | _..._ |
| Q5 signal or artifact | _..._ | _..._ |

At the end of week 1, "not started" on Q4 and Q5 is expected. "Not started" on all five means come find me on Monday.